//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Co
    {
        public int ID_cos { get; set; }
        public int Cod_cont { get; set; }
        public int Cod_carte { get; set; }
    
        public virtual Carte Carte { get; set; }
        public virtual Cont Cont { get; set; }
    }
}
