//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cont
    {
        public Cont()
        {
            this.Cos = new HashSet<Co>();
        }
    
        public int Cod_cont { get; set; }
        public string Email { get; set; }
        public string Parola { get; set; }
    
        public virtual ICollection<Co> Cos { get; set; }
    }
}
