//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editura
    {
        public Editura()
        {
            this.Cartes = new HashSet<Carte>();
        }
    
        public int Cod_edit { get; set; }
        public string Nume { get; set; }
    
        public virtual ICollection<Carte> Cartes { get; set; }
    }
}
