//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibrarieEntities : DbContext
    {
        public LibrarieEntities()
            : base("name=LibrarieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Autori> Autoris { get; set; }
        public DbSet<Carte> Cartes { get; set; }
        public DbSet<Cont> Conts { get; set; }
        public DbSet<Co> Cos { get; set; }
        public DbSet<Editura> Edituras { get; set; }
        public DbSet<Gen> Gens { get; set; }
        public DbSet<Vedere_Carti> Vedere_Carti { get; set; }
        public DbSet<Vedere_Cos> Vedere_Cos { get; set; }
    }
}
