//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vedere_Cos
    {
        public int ID_Cos { get; set; }
        public string Email_Utilizator { get; set; }
        public string Titlu_Carte { get; set; }
    }
}
